### ISSUE TITLE
问

### ISSUE THREAD

**Issue by LTDzhen** [xutianyi1999/picacg-spider#1]
你好，我完全是代码小白，只是我的哔咔被我不小心卸载了，我重新下载后我忘记了用户名了，但是现在哔咔登陆只能用用户名，可以用你的这个方法通过邮箱和密码得到我的用户名嘛，你可以教我怎么用嘛

**Comment by xutianyi1999** [comment]
呃我也不知道怎么拿到，哔咔有官方的tg channel你去上面问问看
